In [1]:
!pip3 install torch
!pip3 install numpy


In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.0.1'

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.dtype

dtype('int64')

In [6]:
type(arr)

numpy.ndarray

In [7]:
x = torch.from_numpy(arr)

In [8]:
type(x)

torch.Tensor

In [9]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [10]:
x.dtype

torch.int64

In [11]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
arr2d = arr2d.reshape(4,3)

In [13]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [14]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [15]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [19]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [20]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Pytorch Basic Part 2
------------------------------------------

In [21]:
new_arr = np.array([1,2,3])

In [22]:
new_arr.dtype

dtype('int64')

In [23]:
torch.tensor(new_arr)

tensor([1, 2, 3])

#### torch.Tensor(new_arr) = torch.FloatTensor(new_arr)  


In [24]:
my_tensor = torch.Tensor(new_arr) # torch.FloatTensor(new_arr)  is it same

In [25]:
my_tensor.dtype

torch.float32

In [26]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [27]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [30]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [31]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [32]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
my_tensor = my_tensor.type(torch.int32)
my_tensor


tensor([1, 2, 3], dtype=torch.int32)

In [34]:
torch.rand(4,3)

tensor([[0.4154, 0.9651, 0.4809],
        [0.5960, 0.5542, 0.1492],
        [0.9715, 0.8308, 0.6428],
        [0.1377, 0.4837, 0.8263]])

In [35]:
torch.randn(4,3)

tensor([[-0.0678,  0.9446,  2.0137],
        [ 1.0041, -0.2096, -0.5936],
        [ 1.0940,  1.3860, -0.9416],
        [-2.9143, -1.6169, -0.3332]])

In [36]:
torch.randint(low=0, high=10,size=(5,5))

tensor([[4, 7, 5, 2, 3],
        [1, 8, 2, 3, 8],
        [1, 3, 4, 1, 5],
        [6, 1, 3, 3, 2],
        [4, 7, 9, 1, 4]])

In [37]:
x = torch.zeros(2,5)
x.shape

torch.Size([2, 5])

In [38]:
torch.rand_like(x)

tensor([[0.5206, 0.0754, 0.0552, 0.4009, 0.8515],
        [0.9217, 0.6994, 0.9598, 0.2163, 0.5733]])

In [39]:
torch.randint_like(x,low=0,high=10)

tensor([[9., 8., 1., 6., 7.],
        [2., 6., 5., 3., 2.]])

In [40]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [41]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [42]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int64')

In [43]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [44]:
torch.Tensor(new_arr)

tensor([1., 2., 3.])