In [24]:
!pip3 install torch
!pip3 install numpy

In [25]:
import torch 
import numpy as np

2. Set the random seed for Numpy and pytorch both to "42"

In [26]:
np.random.seed(42)
torch.manual_seed(42);


3. Create a numpy array called "arr" that contains 6 random integers
between 0 (inclusive) and 5 (exclusive)

In [27]:
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


4. Create a tensor "x" from the array above

In [28]:
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1])


5. Change the dtype of x from "int32" to "int64"

In [31]:
x = x.type(torch.int64)
print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


6. Reshape x into a 3x2 tensor

In [32]:
x = x.reshape(3,2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


7. Return the right-hand column of tensor x

In [42]:
x[:,1]

tensor([4, 4, 1])

8. Without changing x, return a tensor of square values of x

In [43]:
x * x

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

9. <b> Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x </b>

Use Pytorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).
Think about what shape it should have to permit matrix multiplication.

In [51]:
# y = torch.tensor(x)
y = torch.randint(0, 5, (2, 3))
print(y)
# y = x
# print(y)

tensor([[3, 1, 4],
        [3, 1, 4]])


10. Find the matrix product of x and y

In [52]:
x.mm(y)

tensor([[21,  7, 28],
        [18,  6, 24],
        [15,  5, 20]])